# Generated by Django 3.1.2 on 2020-10-28 22:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('category_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('created_at', models.DateField()),
                ('edited_at', models.DateField()),
                ('coord_lat', models.CharField(max_length=10)),
                ('coord_long', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'threats',
            },
        ),
    ]
